INSERT INTO COUNTRY VALUES(1,'Hungary');
INSERT INTO COUNTRY VALUES(2,'Germany');
INSERT INTO CITY VALUES(1,'Budapest',1);
INSERT INTO CITY VALUES(2,'Kaposvar',1);
INSERT INTO CITY VALUES(3,'Balatonboglar',1);
INSERT INTO CITY VALUES(4,'Hamburg',2);
INSERT INTO CITY VALUES(5,'Saltzburg',2);