INSERT INTO COUNTRY VALUES(1,'Hungary');
INSERT INTO COUNTRY VALUES(2,'Germany');

INSERT INTO CITY VALUES(1,'Budapest',1);
INSERT INTO CITY VALUES(2,'Kaposvar',1);
INSERT INTO CITY VALUES(3,'Balatonboglar',1);
INSERT INTO CITY VALUES(4,'Hamburg',2);
INSERT INTO CITY VALUES(5,'Saltzburg',2);

INSERT INTO SPECIES VALUES(1,'Kutya');
INSERT INTO SPECIES VALUES(2,'Macska');

INSERT INTO BREED VALUES(1,'Francia buldog',1);
INSERT INTO BREED VALUES(2,'Magyar Vizsla',1);
INSERT INTO BREED VALUES(3,'Nemetjuhasz',1);
INSERT INTO BREED VALUES(4,'Hazimacska',2);
INSERT INTO BREED VALUES(5,'Vadmacska',2);